/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.ydb.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.ext.generic.model.GenericStructContainer;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.ext.generic.model.GenericView;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

import java.util.ArrayList;
import java.util.List;

/**
 * YDB System View from .sys directory.
 * System views are read-only and cannot be modified.
 * Column structure is loaded dynamically by executing SELECT * FROM .sys/<view_name> LIMIT 0.
 */
public class YDBSystemView extends GenericView {

    private final String fullPath;
    private List<GenericTableColumn> columns;
    private boolean columnsLoaded = false;

    public YDBSystemView(
        GenericStructContainer container,
        @Nullable String viewName,
        @Nullable JDBCResultSet dbResult
    ) {
        super(container, viewName, "SYSTEM VIEW", dbResult);
        // System views are always in .sys directory
        this.fullPath = ".sys/" + (viewName != null ? viewName : "");
        this.columns = new ArrayList<>();
    }

    @NotNull
    public String getFullPath() {
        return fullPath;
    }

    @Override
    public String getFullyQualifiedName(DBPEvaluationContext context) {
        // For SQL context, use the full path with .sys prefix
        if (context == DBPEvaluationContext.DML || context == DBPEvaluationContext.DDL) {
            return "`" + fullPath + "`";
        }
        return super.getFullyQualifiedName(context);
    }

    @Override
    public boolean isView() {
        return true;
    }

    @Override
    public boolean isSystem() {
        // YDB System Views should not be treated as system objects
        // so they are visible without "Show system objects" option
        return false;
    }

    @Override
    public boolean isPersisted() {
        return true;
    }

    /**
     * Add column information obtained from result set metadata.
     * This is called during system view loading to populate column structure.
     *
     * @param columnName Column name
     * @param typeName   SQL type name
     * @param jdbcType   JDBC type code
     * @param precision  Column precision
     * @param scale      Column scale
     * @param nullable   Whether column is nullable
     * @param ordinal    Column ordinal position (1-based)
     */
    public void addColumnInfo(
        @NotNull String columnName,
        @NotNull String typeName,
        int jdbcType,
        int precision,
        int scale,
        boolean nullable,
        int ordinal
    ) {
        GenericTableColumn column = new GenericTableColumn(
            this,
            columnName,
            typeName,
            jdbcType,
            jdbcType,      // sourceType
            ordinal,
            precision,     // columnSize
            precision,     // charLength
            scale > 0 ? scale : null,
            precision > 0 ? precision : null,
            10,            // radix
            !nullable,     // notNull
            null,          // remarks
            null,          // defaultValue
            false,         // autoIncrement
            false          // autoGenerated
        );
        columns.add(column);
        columnsLoaded = true;
    }

    @Override
    public List<? extends GenericTableColumn> getAttributes(@NotNull DBRProgressMonitor monitor) throws DBException {
        if (columnsLoaded && !columns.isEmpty()) {
            return columns;
        }
        // Fall back to parent implementation if columns weren't loaded
        return super.getAttributes(monitor);
    }

    @Override
    public GenericTableColumn getAttribute(@NotNull DBRProgressMonitor monitor, @NotNull String attributeName) throws DBException {
        if (columnsLoaded && !columns.isEmpty()) {
            for (GenericTableColumn column : columns) {
                if (column.getName().equals(attributeName)) {
                    return column;
                }
            }
            return null;
        }
        return super.getAttribute(monitor, attributeName);
    }

    /**
     * Check if columns have been loaded for this system view.
     */
    public boolean isColumnsLoaded() {
        return columnsLoaded;
    }

    /**
     * Get the number of loaded columns.
     */
    public int getColumnCount() {
        return columns.size();
    }
}
