/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.ydb.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.Log;
import org.jkiss.dbeaver.ext.generic.model.GenericStructContainer;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.ext.generic.model.GenericView;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

import tech.ydb.proto.scheme.SchemeOperationProtos;
import tech.ydb.scheme.SchemeClient;

import java.util.ArrayList;
import java.util.List;

/**
 * YDB System View from .sys directory.
 * System views are read-only and cannot be modified.
 * Column structure is loaded dynamically by executing SELECT * FROM .sys/<view_name> LIMIT 0.
 */
public class YDBSystemView extends GenericView implements YDBPermissionHolder {

    private static final Log log = Log.getLog(YDBSystemView.class);

    private final String fullPath;
    private List<GenericTableColumn> columns;
    private boolean columnsLoaded = false;
    private String owner;
    private List<YDBPermissionHolder.PermissionEntry> explicitPermissions = List.of();
    private List<YDBPermissionHolder.PermissionEntry> effectivePermissionsEntries = List.of();
    private boolean permissionsLoaded = false;

    public YDBSystemView(
        GenericStructContainer container,
        @Nullable String viewName,
        @Nullable JDBCResultSet dbResult
    ) {
        super(container, viewName, "SYSTEM VIEW", dbResult);
        // System views are always in .sys directory
        this.fullPath = ".sys/" + (viewName != null ? viewName : "");
        this.columns = new ArrayList<>();
    }

    @NotNull
    public String getFullPath() {
        return fullPath;
    }

    @Override
    public String getFullyQualifiedName(DBPEvaluationContext context) {
        // For SQL context, use the full path with .sys prefix
        if (context == DBPEvaluationContext.DML || context == DBPEvaluationContext.DDL) {
            return "`" + fullPath + "`";
        }
        return super.getFullyQualifiedName(context);
    }

    @Override
    public boolean isView() {
        return true;
    }

    @Override
    public boolean isSystem() {
        // YDB System Views should not be treated as system objects
        // so they are visible without "Show system objects" option
        return false;
    }

    @Override
    public boolean isPersisted() {
        return true;
    }

    /**
     * Add column information obtained from result set metadata.
     * This is called during system view loading to populate column structure.
     *
     * @param columnName Column name
     * @param typeName   SQL type name
     * @param jdbcType   JDBC type code
     * @param precision  Column precision
     * @param scale      Column scale
     * @param nullable   Whether column is nullable
     * @param ordinal    Column ordinal position (1-based)
     */
    public void addColumnInfo(
        @NotNull String columnName,
        @NotNull String typeName,
        int jdbcType,
        int precision,
        int scale,
        boolean nullable,
        int ordinal
    ) {
        GenericTableColumn column = new GenericTableColumn(
            this,
            columnName,
            typeName,
            jdbcType,
            jdbcType,      // sourceType
            ordinal,
            precision,     // columnSize
            precision,     // charLength
            scale > 0 ? scale : null,
            precision > 0 ? precision : null,
            10,            // radix
            !nullable,     // notNull
            null,          // remarks
            null,          // defaultValue
            false,         // autoIncrement
            false          // autoGenerated
        );
        columns.add(column);
        columnsLoaded = true;
    }

    @Nullable
    @Property(viewable = false, order = 100)
    public String getOwner() {
        return owner;
    }

    @NotNull
    @Override
    public List<YDBPermissionHolder.PermissionEntry> getExplicitPermissions() {
        return explicitPermissions;
    }

    @NotNull
    @Override
    public List<YDBPermissionHolder.PermissionEntry> getEffectivePermissions() {
        return effectivePermissionsEntries;
    }

    @Override
    public void ensurePermissionsLoaded(@NotNull DBRProgressMonitor monitor) throws DBException {
        if (permissionsLoaded) {
            return;
        }
        try (JDBCSession session = DBUtils.openMetaSession(monitor, getDataSource(), "Load permissions")) {
            java.sql.Connection conn = session.getOriginal();
            if (conn.isWrapperFor(tech.ydb.jdbc.YdbConnection.class)) {
                tech.ydb.jdbc.YdbConnection ydbConn = conn.unwrap(tech.ydb.jdbc.YdbConnection.class);
                tech.ydb.jdbc.context.YdbContext ctx = ydbConn.getCtx();
                loadPermissions(ctx.getSchemeClient(), ctx.getPrefixPath());
            }
        } catch (Exception e) {
            log.debug("Failed to load permissions: " + e.getMessage());
        }
    }

    synchronized void loadPermissions(
        @NotNull SchemeClient schemeClient,
        @NotNull String prefixPath
    ) {
        if (permissionsLoaded) {
            return;
        }
        String absolutePath = prefixPath + "/" + fullPath;
        SchemeOperationProtos.Entry entry = YDBDescribeHelper.describePath(schemeClient, absolutePath);
        if (entry != null) {
            owner = entry.getOwner();
            explicitPermissions = YDBDescribeHelper.toPermissionEntries(entry.getPermissionsList());
            effectivePermissionsEntries = YDBDescribeHelper.toPermissionEntries(entry.getEffectivePermissionsList());
        }
        permissionsLoaded = true;
    }

    @Override
    public void resetPermissions() {
        permissionsLoaded = false;
        owner = null;
        explicitPermissions = new java.util.ArrayList<>();
        effectivePermissionsEntries = new java.util.ArrayList<>();
    }

    @Override
    public void modifyPermissions(
        @NotNull DBRProgressMonitor monitor,
        @NotNull java.util.List<YDBPermissionHolder.PermissionAction> actions,
        boolean clearPermissions,
        @Nullable Boolean interruptInheritance
    ) throws DBException {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, getDataSource(), "Modify permissions")) {
            java.sql.Connection conn = session.getOriginal();
            if (conn.isWrapperFor(tech.ydb.jdbc.YdbConnection.class)) {
                tech.ydb.jdbc.YdbConnection ydbConn = conn.unwrap(tech.ydb.jdbc.YdbConnection.class);
                tech.ydb.jdbc.context.YdbContext ctx = ydbConn.getCtx();
                String absolutePath = ctx.getPrefixPath() + "/" + fullPath;
                boolean ok = YDBDescribeHelper.modifyPermissions(
                    ctx.getGrpcTransport(), absolutePath, actions, clearPermissions, interruptInheritance);
                if (!ok) {
                    throw new DBException("Failed to modify permissions on " + absolutePath);
                }
                resetPermissions();
            }
        } catch (java.sql.SQLException e) {
            throw new DBException("Failed to modify permissions", e);
        }
    }

    @Override
    public List<? extends GenericTableColumn> getAttributes(@NotNull DBRProgressMonitor monitor) throws DBException {
        // Do not fall back to super.getAttributes() — it uses JDBC getColumns()
        // which calls listTables() and recursively lists all directories including .tmp,
        // causing UNAUTHORIZED errors
        return columnsLoaded ? columns : List.of();
    }

    @Override
    public GenericTableColumn getAttribute(@NotNull DBRProgressMonitor monitor, @NotNull String attributeName) throws DBException {
        if (columnsLoaded) {
            for (GenericTableColumn column : columns) {
                if (column.getName().equals(attributeName)) {
                    return column;
                }
            }
        }
        return null;
    }

    /**
     * Check if columns have been loaded for this system view.
     */
    public boolean isColumnsLoaded() {
        return columnsLoaded;
    }

    /**
     * Get the number of loaded columns.
     */
    public int getColumnCount() {
        return columns.size();
    }
}
